AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  priceDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Prices
      AttributeDefinitions:
        - AttributeName: Asset
          AttributeType: S
        - AttributeName: Price
          AttributeType: S
      KeySchema:
        - AttributeName: Asset
          KeyType: HASH
        - AttributeName: Price
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  priceWriterAppLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/price-writer.priceWriterLambdaHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that set prices on schedule
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBWritePolicy:
            TableName: !Ref priceDbTable
      Events:
        PriceApp:
          Type: Api
          Properties:
            Path: /asset/update
            Method: post

  priceReaderAppLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/price-reader.priceReaderLambdaHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that retrieves prices by assets and period
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref priceDbTable
      Events:
        PriceApp:
          Type: Api
          Properties:
            Path: /asset/{assetId}/price_changes
            Method: get
            RequestParameters:
              - method.request.path.assetId:
                  Required: true
                  Caching: false
              - method.request.querystring.period:
                  Required: true
                  Caching: false

Outputs:
  PriceAppURL:
    Description: "API endpoint URL for our Price App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/asset/"
  TableName:
    Value: !Ref "priceDbTable"
    Description: Table name of the newly created DynamoDB table
